-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.activity_logs (
 id uuid NOT NULL DEFAULT gen_random_uuid(),
 organization_id uuid NOT NULL,
 user_id uuid,
 action text NOT NULL,
 resource_type text NOT NULL,
 resource_id uuid,
 payload jsonb NOT NULL DEFAULT '{}'::jsonb,
 ip_address inet,
 user_agent text,
 created_at timestamp with time zone NOT NULL DEFAULT now(),
 CONSTRAINT activity_logs_pkey PRIMARY KEY (id),
 CONSTRAINT activity_logs_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
 CONSTRAINT activity_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.automation_runs (
 id uuid NOT NULL DEFAULT gen_random_uuid(),
 organization_id uuid NOT NULL,
 automation_id uuid NOT NULL,
 status USER-DEFINED NOT NULL DEFAULT 'pending'::run_status,
 trigger_type USER-DEFINED NOT NULL DEFAULT 'manual'::run_trigger_type,
 triggered_by uuid,
 started_at timestamp with time zone,
 finished_at timestamp with time zone,
 duration_ms integer,
 logs jsonb NOT NULL DEFAULT '[]'::jsonb,
 error_message text,
 output jsonb,
 created_at timestamp with time zone NOT NULL DEFAULT now(),
 CONSTRAINT automation_runs_pkey PRIMARY KEY (id),
 CONSTRAINT automation_runs_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
 CONSTRAINT automation_runs_automation_id_fkey FOREIGN KEY (automation_id) REFERENCES public.automations(id),
 CONSTRAINT automation_runs_triggered_by_fkey FOREIGN KEY (triggered_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.automation_templates (
 id uuid NOT NULL DEFAULT gen_random_uuid(),
 name text NOT NULL,
 slug text NOT NULL UNIQUE,
 description text,
 category text,
 icon text,
 config_schema jsonb NOT NULL DEFAULT '{}'::jsonb,
 default_config jsonb NOT NULL DEFAULT '{}'::jsonb,
 is_active boolean NOT NULL DEFAULT true,
 created_at timestamp with time zone NOT NULL DEFAULT now(),
 updated_at timestamp with time zone NOT NULL DEFAULT now(),
 CONSTRAINT automation_templates_pkey PRIMARY KEY (id)
);
CREATE TABLE public.automations (
 id uuid NOT NULL DEFAULT gen_random_uuid(),
 organization_id uuid NOT NULL,
 template_id uuid,
 name text NOT NULL,
 description text,
 status USER-DEFINED NOT NULL DEFAULT 'draft'::automation_status,
 config jsonb NOT NULL DEFAULT '{}'::jsonb,
 trigger_type USER-DEFINED NOT NULL DEFAULT 'manual'::run_trigger_type,
 cron_expression text,
 webhook_secret text,
 last_run_at timestamp with time zone,
 next_run_at timestamp with time zone,
 created_by uuid,
 created_at timestamp with time zone NOT NULL DEFAULT now(),
 updated_at timestamp with time zone NOT NULL DEFAULT now(),
 CONSTRAINT automations_pkey PRIMARY KEY (id),
 CONSTRAINT automations_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
 CONSTRAINT automations_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.automation_templates(id),
 CONSTRAINT automations_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.bookings (
 id uuid NOT NULL DEFAULT gen_random_uuid(),
 organization_id uuid NOT NULL,
 lead_id uuid,
 first_name text NOT NULL,
 last_name text,
 email text NOT NULL,
 phone text,
 company text,
 scheduled_at timestamp with time zone NOT NULL,
 duration_minutes integer NOT NULL DEFAULT 30,
 timezone text NOT NULL DEFAULT 'Europe/Madrid'::text,
 meeting_url text,
 status USER-DEFINED NOT NULL DEFAULT 'pending'::booking_status,
 notes text,
 internal_notes text,
 cancelled_reason text,
 assigned_to uuid,
 created_at timestamp with time zone NOT NULL DEFAULT now(),
 updated_at timestamp with time zone NOT NULL DEFAULT now(),
 CONSTRAINT bookings_pkey PRIMARY KEY (id),
 CONSTRAINT bookings_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
 CONSTRAINT bookings_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES public.leads(id),
 CONSTRAINT bookings_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES public.profiles(id)
);
CREATE TABLE public.integrations (
 id uuid NOT NULL DEFAULT gen_random_uuid(),
 organization_id uuid NOT NULL,
 provider text NOT NULL,
 status USER-DEFINED NOT NULL DEFAULT 'disconnected'::integration_status,
 metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
 vault_secret_id text,
 connected_at timestamp with time zone,
 expires_at timestamp with time zone,
 last_synced_at timestamp with time zone,
 error_message text,
 created_at timestamp with time zone NOT NULL DEFAULT now(),
 updated_at timestamp with time zone NOT NULL DEFAULT now(),
 CONSTRAINT integrations_pkey PRIMARY KEY (id),
 CONSTRAINT integrations_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.invoices (
 id uuid NOT NULL DEFAULT gen_random_uuid(),
 organization_id uuid NOT NULL,
 project_id uuid,
 milestone_id uuid,
 number text NOT NULL,
 status USER-DEFINED NOT NULL DEFAULT 'draft'::invoice_status,
 subtotal_cents integer NOT NULL DEFAULT 0,
 tax_cents integer NOT NULL DEFAULT 0,
 total_cents integer NOT NULL DEFAULT 0,
 paid_cents integer NOT NULL DEFAULT 0,
 currency character NOT NULL DEFAULT 'EUR'::bpchar,
 issued_at timestamp with time zone,
 due_at timestamp with time zone,
 paid_at timestamp with time zone,
 pdf_path text,
 client_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
 line_items jsonb NOT NULL DEFAULT '[]'::jsonb,
 notes text,
 internal_notes text,
 external_ref text,
 created_at timestamp with time zone NOT NULL DEFAULT now(),
 updated_at timestamp with time zone NOT NULL DEFAULT now(),
 CONSTRAINT invoices_pkey PRIMARY KEY (id),
 CONSTRAINT invoices_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
 CONSTRAINT invoices_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
 CONSTRAINT invoices_milestone_id_fkey FOREIGN KEY (milestone_id) REFERENCES public.project_milestones(id)
);
CREATE TABLE public.leads (
 id uuid NOT NULL DEFAULT gen_random_uuid(),
 organization_id uuid NOT NULL,
 first_name text NOT NULL,
 last_name text,
 email text NOT NULL,
 phone text,
 company text,
 website text,
 message text,
 status USER-DEFINED NOT NULL DEFAULT 'new'::lead_status,
 source text,
 budget_cents integer,
 assigned_to uuid,
 lost_reason text,
 converted_to_booking_id uuid,
 notes text,
 tags ARRAY NOT NULL DEFAULT '{}'::text[],
 created_at timestamp with time zone NOT NULL DEFAULT now(),
 updated_at timestamp with time zone NOT NULL DEFAULT now(),
 CONSTRAINT leads_pkey PRIMARY KEY (id),
 CONSTRAINT leads_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
 CONSTRAINT leads_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES public.profiles(id),
 CONSTRAINT fk_leads_booking FOREIGN KEY (converted_to_booking_id) REFERENCES public.bookings(id)
);
CREATE TABLE public.notifications (
 id uuid NOT NULL DEFAULT gen_random_uuid(),
 organization_id uuid NOT NULL,
 user_id uuid NOT NULL,
 category USER-DEFINED NOT NULL,
 severity USER-DEFINED NOT NULL DEFAULT 'info'::notification_severity,
 title text NOT NULL,
 body text,
 resource_type text,
 resource_id uuid,
 action_url text,
 read_at timestamp with time zone,
 created_at timestamp with time zone NOT NULL DEFAULT now(),
 CONSTRAINT notifications_pkey PRIMARY KEY (id),
 CONSTRAINT notifications_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
 CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.organization_members (
 id uuid NOT NULL DEFAULT gen_random_uuid(),
 organization_id uuid NOT NULL,
 user_id uuid NOT NULL,
 role USER-DEFINED NOT NULL DEFAULT 'member'::organization_role,
 invited_by uuid,
 accepted_at timestamp with time zone,
 created_at timestamp with time zone NOT NULL DEFAULT now(),
 updated_at timestamp with time zone NOT NULL DEFAULT now(),
 CONSTRAINT organization_members_pkey PRIMARY KEY (id),
 CONSTRAINT organization_members_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
 CONSTRAINT organization_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
 CONSTRAINT organization_members_invited_by_fkey FOREIGN KEY (invited_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.organizations (
 id uuid NOT NULL DEFAULT gen_random_uuid(),
 name text NOT NULL,
 slug text NOT NULL UNIQUE,
 logo_url text,
 website text,
 plan USER-DEFINED NOT NULL DEFAULT 'free'::organization_plan,
 status USER-DEFINED NOT NULL DEFAULT 'active'::organization_status,
 stripe_customer_id text UNIQUE,
 trial_ends_at timestamp with time zone,
 settings jsonb NOT NULL DEFAULT '{}'::jsonb,
 created_at timestamp with time zone NOT NULL DEFAULT now(),
 updated_at timestamp with time zone NOT NULL DEFAULT now(),
 CONSTRAINT organizations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.profiles (
 id uuid NOT NULL,
 full_name text,
 avatar_url text,
 phone text,
 locale text NOT NULL DEFAULT 'es'::text,
 timezone text NOT NULL DEFAULT 'Europe/Madrid'::text,
 onboarded_at timestamp with time zone,
 created_at timestamp with time zone NOT NULL DEFAULT now(),
 updated_at timestamp with time zone NOT NULL DEFAULT now(),
 CONSTRAINT profiles_pkey PRIMARY KEY (id),
 CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.project_milestones (
 id uuid NOT NULL DEFAULT gen_random_uuid(),
 organization_id uuid NOT NULL,
 project_id uuid NOT NULL,
 name text NOT NULL,
 description text,
 status USER-DEFINED NOT NULL DEFAULT 'pending'::milestone_status,
 position integer NOT NULL DEFAULT 0,
 due_at timestamp with time zone,
 completed_at timestamp with time zone,
 amount_cents integer,
 created_at timestamp with time zone NOT NULL DEFAULT now(),
 updated_at timestamp with time zone NOT NULL DEFAULT now(),
 CONSTRAINT project_milestones_pkey PRIMARY KEY (id),
 CONSTRAINT project_milestones_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
 CONSTRAINT project_milestones_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id)
);
CREATE TABLE public.projects (
 id uuid NOT NULL DEFAULT gen_random_uuid(),
 organization_id uuid NOT NULL,
 lead_id uuid,
 name text NOT NULL,
 description text,
 status USER-DEFINED NOT NULL DEFAULT 'draft'::project_status,
 starts_at timestamp with time zone,
 deadline_at timestamp with time zone,
 completed_at timestamp with time zone,
 budget_cents integer,
 price_cents integer,
 owner_id uuid,
 tags ARRAY NOT NULL DEFAULT '{}'::text[],
 settings jsonb NOT NULL DEFAULT '{}'::jsonb,
 created_at timestamp with time zone NOT NULL DEFAULT now(),
 updated_at timestamp with time zone NOT NULL DEFAULT now(),
 CONSTRAINT projects_pkey PRIMARY KEY (id),
 CONSTRAINT projects_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
 CONSTRAINT projects_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES public.leads(id),
 CONSTRAINT projects_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES public.profiles(id)
);
